apiVersion: v1
kind: Pod
metadata:
  name: api
  namespace: taskflow
  labels:
    app: taskflow
    component: api
spec:
  restartPolicy: Always
  containers:
    - name: api
      image: docker.io/rchrdkvcs/taskflow-api:1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 3000
      env:
        - name: NODE_ENV
          value: production
        - name: APP_ENV
          value: production
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: 10.42.1.5
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: taskflow
        - name: DB_USER
          value: taskflow
        - name: DB_PASSWORD
          value: taskflow-test
        - name: DB_CONNECT_RETRIES
          value: "5"
        - name: DB_CONNECT_INTERVAL_MS
          value: "2000"
        - name: STRESS_MAX_MS
          value: "5000"
        - name: SHUTDOWN_TIMEOUT_MS
          value: "8000"
