apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: taskflow
  labels:
    app: taskflow
    component: db
spec:
  restartPolicy: Always
  containers:
    - name: postgres
      image: docker.io/postgres:18-alpine
      imagePullPolicy: IfNotPresent
      ports:
        - name: postgres
          containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: taskflow
        - name: POSTGRES_USER
          value: taskflow
        - name: POSTGRES_PASSWORD
          value: taskflow-test
